### 
Candy JS
###

Candy = @Candy = {}

Candy.httpGet = (url) ->
  xmlhttp = undefined
  @url = url
  if window.XMLHttpRequest
    xmlhttp = new XMLHttpRequest
  else
    xmlhttp = new ActiveXObject('Microsoft.XMLHTTP')

  xmlhttp.onreadystatechange = ->
    if xmlhttp.readyState == XMLHttpRequest.DONE
      if xmlhttp.status == 200
        document.getElementById('myDiv').innerHTML = xmlhttp.responseText
      else if xmlhttp.status == 400
        alert 'There was an error 400'
      else
        console.log 'Error something else other than 200 was returned'
    return

  output = xmlhttp.open('GET', @url, true)
  xmlhttp.send()
  output

# Candy.httpGet( URL )

Candy.shuffle = (contents) ->
  @contents = contents
  output = @contents[Math.floor(Math.random() * @contents.length)]
  output

# Candy.shuffle( Array )

Candy.rand = (arg, arg_2) ->
  output = Math.floor(Math.random() * (arg - arg_2 + 1)) + arg_2
  output

# Candy.rand( First Number, Second Number 

Candy.toVar = (arg, contains) ->
  arg = @arg
  contains = @contains
  window[arg] = contains
  return

Candy.write = (arg, arg2) ->
  `var w`
  if @arg2 == true
    console.log @arg
  else if @arg2 == undefined
    w = document.createElement('div')
    w.textContent = @arg
    document.body.appendChild w
  else
    w = document.createElement('div')
    w.textContent = @arg
    document.body.appendChild w
  return

Candy.time = ->
  d = new Date
  hour = if d.getHours() == 0 then 12 else if d.getHours() > 12 then d.getHours() - 12 else d.getHours()
  min = if d.getMinutes() < 10 then '0' + d.getMinutes() else d.getMinutes()
  ampm = if d.getHours() < 12 then 'AM' else 'PM'
  candy_time = hour + ':' + min + ' ' + ampm
  candy_time

# Candy.time()

Candy.contains = (array, value) ->
  @array = array
  @value = value
  if @array.indexOf(@value) != -1
    true
  else
    false

Candy.newList = (items, tags) ->
  @tags = tags
  @items = items
  # Establish the array which acts as a data source for the list
  listData = @items
  # Make a container element for the list - which is a <div>
  # You don't actually need this container to make it work
  listContainer = document.createElement('div')
  # add it to the page
  document.getElementsByTagName('body')[0].appendChild listContainer
  # Make the list itself which is a <ul>
  listElement = document.createElement(@tags[0])
  # add it to the page
  listContainer.appendChild listElement
  # Set up a loop that goes through the items in listItems one at a time
  numberOfListItems = listData.length
  i = 0
  while i < numberOfListItems
    # create a <li> for each one.
    listItem = document.createElement(@tags[1])
    # add the item text
    listItem.innerHTML = listData[i]
    # add listItem to the listElement
    listElement.appendChild listItem
    ++i
  return

# Only Works with HTML... Candy.newMenu(["JAN", "FEB"], ["ul", "li"])

Candy.getIP = ->
  '<!--#echo var="REMOTE_ADDR"-->'

console.log Candy.time()
# Only Works with HTML... Candy.getIP()

# ---
# generated by js2coffee 2.1.0
